fix dollar signs in codeblocks breaking when running through Prism
empress/ember-showdown-prism pull request #13
Opened 2020-12-22 20:24 UTC by nickschot

Our prism showdown plugin was breaking dollar signs because Prism was interfering with the "custom characters " showdown uses during parsing. This PR temporarily reinstates the normal characters so Prism can do it's thing and then restores the "custom characters" afterwards so showdown doesn't break.

2020-12-23 10:53 UTC, locks approved these changes

2020-12-23 12:40 UTC, mansona requested changes
Just let whoever wants to merge this know that I've discussed with @nickschot about adding "tests". There are no real tests in this repo yet but we need to at least add a demo of this problem to the dummy app, that way we could add percy as a cover for regression 👍

2020-12-23 12:41 UTC, mansona commented
also when the demo is added feel free to dismiss my review 👍

2021-08-12 15:43 UTC, mansona approved these changes

2021-08-12 16:13 UTC, merged